/* tslint:disable */
/* eslint-disable */
/**
 * Metuljmania API
 * Metuljmania ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditPilotDTO
 */
export interface EditPilotDTO {
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    eventId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EditPilotDTO
     */
    female?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    licence?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    fai?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    civlid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    birthDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    mobilePhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    address?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    flyingSince?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    team?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    nation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    glider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    safetyClass?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    gliderColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    insuranceCompany?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    policyNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    ippifileId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    licenceFileId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    checkFileId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    signedApplicationFileId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EditPilotDTO
     */
    unSignedApplicationFileId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    sponsors?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditPilotDTO
     */
    lastName?: string | null;
}


