/* tslint:disable */
/* eslint-disable */
/**
 * Metuljmania API
 * Metuljmania ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BasicInfoDTO } from './basic-info-dto';

/**
 * 
 * @export
 * @interface PilotDTO
 */
export interface PilotDTO {
    /**
     * 
     * @type {number}
     * @memberof PilotDTO
     */
    id?: number;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof PilotDTO
     */
    event?: BasicInfoDTO;
    /**
     * 
     * @type {boolean}
     * @memberof PilotDTO
     */
    female?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    licence?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    fai?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    civlid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    birthDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    mobilePhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    address?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PilotDTO
     */
    flyingSince?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    team?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    nation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    glider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    safetyClass?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    gliderColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    insuranceCompany?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    policyNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    modifiedDate?: string | null;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof PilotDTO
     */
    ippifile?: BasicInfoDTO;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof PilotDTO
     */
    licenceFile?: BasicInfoDTO;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof PilotDTO
     */
    checkFile?: BasicInfoDTO;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof PilotDTO
     */
    signedApplicationFile?: BasicInfoDTO;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof PilotDTO
     */
    unSignedApplicationFile?: BasicInfoDTO;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    sponsors?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    lastName?: string | null;
}


